- macro: traefik_consider_syscalls
  condition: (evt.num < 0)

- macro: app_traefik
  condition: container and container.image startswith "traefik"

# Restricting listening ports to selected set

- list: traefik_allowed_inbound_ports_tcp
  items: [443, 80, 8080]

- rule: Unexpected inbound tcp connection traefik
  desc: Detect inbound traffic to traefik using tcp on a port outside of expected set
  condition: inbound and evt.rawres >= 0 and not fd.sport in (traefik_allowed_inbound_ports_tcp) and app_traefik
  output: Inbound network connection to traefik on unexpected port (command=%proc.cmdline pid=%proc.pid connection=%fd.name sport=%fd.sport user=%user.name %container.info image=%container.image)
  priority: NOTICE

# Restricting spawned processes to selected set

- list: traefik_allowed_processes
  items: ["traefik"]

- rule: Unexpected spawned process traefik
  desc: Detect a process started in a traefik container outside of an expected set
  condition: spawned_process and not proc.name in (traefik_allowed_processes) and app_traefik
  output: Unexpected process spawned in traefik container (command=%proc.cmdline pid=%proc.pid user=%user.name %container.info image=%container.image)
  priority: NOTICE
